create table players(
p_id integer primary key,
name varchar(80) unique,
current_team varchar(80),
position varchar(20),
create_at defult current_timestamp,
update_at default current_timestamp
);
create table pitcher_scores(
pys_id integer primary key,
p_id integer,
year varchar(40),
term_name varchar(40),
defense_rate real,
game_number integer,
win integer,
lose integer,
hold_save integer,
pitching_time varchar(80),
hit integer,
homerun integer,
strikeout integer,
four integer,
dead integer,
point integer,
create_at defult current_timestamp,
update_at default current_timestamp,
foreign key(p_id) references players(p_id)
);
create table fielder_scores(
pys_id integer primary key,
p_id integer,
year varchar(40),
term_name varchar(40),
batting_rate real,
game_number integer,
stroke_cnt integer,
hit        integer,
homerun    integer,
hit_point  integer,
score      integer,
struck_out integer,
four       integer,
dead       integer,
sacrifice  integer,
sacrifice_fly    integer,
steal_base       integer,
create_at defult current_timestamp,
update_at default current_timestamp,
foreign key(p_id) references players(p_id)
);
